version: '3.8'

services:

  db:
    container_name: mysql
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:

      MYSQL_DATABASE: 'stationSki'
      MYSQL_ROOT_PASSWORD: ''  # Set to an empty string for an empty password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
      - $PWD/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  spring_app:
    image: raniahmidet/raniahmidet-5DS2-G2-skistation:${IMAGE_TAG}
    container_name: gestion_station_ski
    depends_on:
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/stationSki?createDatabaseIfNotExist=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
    ports:
      - "8089:8089"

volumes:
  mysql_data:
    
